version: "3.8"
services:
  app:
    container_name: webContainer
    build: .
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongodb:27017
    ports:
      - '4000:4000'
    links:
      - mongo

  mongo:
    container_name: dbContainer
    image: mongo
    ports:
      - '27074:27017'



